### ISSUE TITLE
It will take a few more time to create zoom Meeting links than expected.  

### ISSUE THREAD

**Issue by petro1912** [petro1912/clinic-scheduling-system#3]
Doctors can create zoom meeting links for booked patient's appointment for further procedure.
However when doctors click the "create link" button, it will take a few time, so I think it has to be resolved using loader icon to notify the doctor that system is processing at that moment.

**Comment by polaris322** [comment]
Hello, @petro1912 !
I already checked it, yesterday and it was fixed in last commit.
Please pull again and check carefully.
Thanks.

**Comment by petro1912** [comment]
Ok, I missed it.
I will update soon.
